
FROM node:18-alpine

WORKDIR /app

# Копируем package.json отдельно для кэширования
COPY package.json package-lock.json ./
RUN npm install

# Копируем исходный код
COPY . .

# Запускаем dev сервер
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]