# Generated by Django 5.2.7 on 2025-11-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="location",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publication",
            name="price",
            field=models.CharField(blank=True),
        ),
    ]
