# Generated by Django 5.2.7 on 2025-11-12 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_publication_location_alter_publication_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="publication",
            name="slug",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications_status",
                to="main.status",
            ),
        ),
    ]
