# Generated by Django 5.2.8 on 2026-01-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publicationimage",
            old_name="product",
            new_name="publication",
        ),
        migrations.AlterField(
            model_name="publication",
            name="main_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="publications/main/"
            ),
        ),
        migrations.AlterField(
            model_name="publicationimage",
            name="image",
            field=models.ImageField(upload_to="publications/extra/"),
        ),
    ]
