# Generated by Django 5.2.8 on 2026-01-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="main_image",
        ),
    ]
