# Generated by Django 5.2.8 on 2026-01-05 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_initial"),
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="status_name",
        ),
        migrations.AlterField(
            model_name="publication",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chats.chat",
            ),
        ),
    ]
