# Generated by Django 5.2.8 on 2026-01-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_publication_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="publicationtype",
            name="slug",
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
