# Generated by Django 5.2.8 on 2026-01-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_publication_status_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="main_image",
            field=models.ImageField(null=True, upload_to="publications/main/"),
        ),
    ]
