# Generated by Django 5.2.8 on 2026-01-06 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0001_initial"),
        ("main", "0001_initial"),
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="offers.offer"
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.publication"
            ),
        ),
    ]
