# Generated by Django 5.2.8 on 2026-01-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="offer",
        ),
    ]
