# Generated by Django 5.2.8 on 2026-01-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="text",
        ),
    ]
