# Generated by Django 5.2.8 on 2026-01-06 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_remove_chat_offer"),
        ("offers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="chat",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="chats.chat"
            ),
            preserve_default=False,
        ),
    ]
