# Generated by Django 5.2.8 on 2026-01-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0003_offer_chat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="offer_author",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="publication_author",
        ),
    ]
